
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbCommon
{

     private readonly CommonConfig _data;

     public CommonConfig Data => _data;

    public TbCommon(JSONNode _buf)
    {
        int n = _buf.Count;
        if (n != 1) throw new SerializationException("table mode=one, but size != 1");
        { if(!_buf[0].IsObject) { throw new SerializationException(); }  _data = CommonConfig.DeserializeCommonConfig(_buf[0]);  }
    }


    /// <summary>
    /// 参数1
    /// </summary>
     public int X1 => _data.X1;
    /// <summary>
    /// 道具
    /// </summary>
     public int X2 => _data.X2;
     public int X3 => _data.X3;
     public int X4 => _data.X4;
     public int X5 => _data.X5;
     public int X6 => _data.X6;
     public System.Collections.Generic.List<int> X7 => _data.X7;
    
    public void ResolveRef(Tables tables)
    {
        _data.ResolveRef(tables);
    }
}

}

